### USER REQUESTS

GET http://localhost:3500/users

###

POST http://localhost:3500/users
Content-Type: application/json

{
    "username": "Kyle",
    "password": "123456",
    "roles": ["Employee"]
}

###

GET http://localhost:3500/users/63c8874956092d795b251e14

###

PATCH http://localhost:3500/users
Content-Type: application/json

{
    "id": "63c8874956092d795b251e14",
    "username": "Kyle",
    "roles": ["Grunt"],
    "active": true
}

###

DELETE http://localhost:3500/users
Content-Type: application/json

{
    "id": "63c73db09778fa8e0eb9dec6"
}

###

GET http://localhost:3500/users


### PRODUCT CATEGORY REQUESTS

GET http://localhost:3500/users/63c8874956092d795b251e14/productCategories