### USER REQUESTS

GET http://localhost:3500/users

###

POST http://localhost:3500/users
Content-Type: application/json

{
    "username": "Kyle",
    "password": "123456",
    "roles": ["Employee"]
}

###

GET http://localhost:3500/users/63c8874956092d795b251e14

###

PATCH http://localhost:3500/users
Content-Type: application/json

{
    "id": "63c8874956092d795b251e14",
    "username": "Kyle",
    "roles": ["Grunt"],
    "active": true
}

###

DELETE http://localhost:3500/users
Content-Type: application/json

{
    "id": "63cbe0e930bb5273d8bdaaf0"
}

###

GET http://localhost:3500/users


### PRODUCT CATEGORY REQUESTS

PUT http://localhost:3500/users/63cbe7045558bd7584dde1eb/productCategories
Content-Type: application/json

{
    "name": "My first sdfs"
}


### 

PATCH http://localhost:3500/users/63cbe7045558bd7584dde1eb/productCategories/63cbe918b0e115217b334608
Content-Type: application/json

{
    "name": "Record change?"
}

### 

DELETE http://localhost:3500/users/63cbe7045558bd7584dde1eb/productCategories/63cbe83135a2696c1c5d6049